### ISSUE TITLE
Remove是个危险操作，使用有隐患

### ISSUE THREAD

**Issue by left2right** [edwingeng/doublejump#1]
场景：
        假设有A,B,C,D,E五个节点提供服务，某时刻Remove了节点C，此时数据被hash到A,B,D,E四个节点，假设之后又过了一段时间，B发生了重启（无论B是从类似etcd中获得节点列表，还是通过其他方法发现其他存活的节点），那此时B节点对数据的hash是和其他节点完全不一致的。
       假设再Remove节点C后，对A，B，D，E均调用Shrink，则Shrink之后各节点对数据的hash，和节点移除前基本是完全不一样的（测试和推理均可说明），这也是不合适的（违背了迁移数据最少的初衷）
       感觉上面场景的问题，解决办法应该是，在B重启后，仍然获取A，B，C，D，E节点，然后调用Remove C节点。但这个在集群比较大时，就比较混乱了。
      感觉这个实现应该是节点替换的场景比较适用，比如B节点挂了，立即添加F节点替换B。

====上面的推测分析是否正确，如何解决比较合适？

**Comment by edwingeng** [comment]
分析得对。doublejump 实际是面向长连接服务器写的，客户端通过长连接连到网关上，doublejump 负责分发长连接的请求。在这样的使用场景下，网关之间的 doublejump 状态是否一致并不重要，只要在网关内部、对一个特定的连接能做到稳定分发就可以了。因为不能保证服务器之间状态一致，所以目前的实现不能用于短连接网关。

**Comment by left2right** [comment]
> 分析得对。doublejump 实际是面向长连接服务器写的，客户端通过长连接连到网关上，doublejump 负责分发长连接的请求。在这样的使用场景下，网关之间的 doublejump 状态是否一致并不重要，只要在网关内部、对一个特定的连接能做到稳定分发就可以了。因为不能保证服务器之间状态一致，所以目前的实现不能用于短连接网关。

了解，不太适合对各服务节点状态一致要求高的场景，不过这个实现很赞
